name = jc_special
description = JustCraft Special Nodes
author = erstazi
version = 1.0.1
depends = default, beds
optional_depends = ethereal, animalia, creatura, homedecor, homedecor_inbox, homedecor_clocks, homedecor_exterior, wine, cottages, unified_inventory, mobs, mobs_monster, xban2, areas, jc_welcome